/*global jQuery, $, _, AjaxSolr, EUMSSI*/
(function ($) {

	/**
	 * Widget that manages the Related Filters generated by the Service,
	 * @type {A|*|void}
	 * @augments AjaxSolr.AbstractWidget
	 */
	AjaxSolr.FilterRelatedContentWidget = AjaxSolr.AbstractWidget.extend({

		start:0,	//Reset the pagination with doRequest on this Widget

		init: function(){
			this.$target = $(this.target);

			var template = _.template($("#filter-related-content-tpl").html());
			this.$target.html(template());

			this.$entities = this.$target.find(".entities");
			this.$keywords = this.$target.find(".keywords");
			this.$queries = this.$target.find(".queries");

			//EVENTS
			EUMSSI.EventManager.on("getRelatedFilters", this._retrieveRelatedFilters.bind(this));
			this.$target.find(".search").button().on("click", this._onSearchClick.bind(this));
		},

		beforeRequest: function(){
			return true;
		},

		afterRequest: function(){
			return true;
		},

		_onGetRelatedFilters : function(response){
			EUMSSI.EventManager.trigger("OpenFilter");
			this.$entities.empty();
			this.$keywords.empty();
			this.$queries.empty();

			_.each(response.entities, function(entity){
				this.$entities.append(this._renderElementRow(entity, "entity"));
			}.bind(this));

			_.each(response.keywords, function(keyword){
				this.$keywords.append(this._renderElementRow(keyword, "keyword"));
			}.bind(this));

			//Build a Editable select
			_.each(response.queries, function(query){
				var item = $("<a>").html(query);
				item.click(this._addQueryToFilter);
				this.$queries.append(item);
			}.bind(this));

		},

		_renderElementRow : function(item, type){
			var entityTpl = _.template($("#filter-related-content-row-tpl").html());
			return entityTpl({
				item : item,
				type : type
			});
		},

		_onSearchClick : function(){
			//Clean previous filters
			EUMSSI.FilterManager.removeFilterByWidget(this.id, true);

			//Add checked items to filter
			var checkedItems = this.$target.find("input[type='checkbox']:checked");
			checkedItems.each(function(index, el){
				var value = $(el).closest(".item-row").attr("data-value");
				this._addItemToFilter(value);
			}.bind(this));

			//Do request
			EUMSSI.Manager.doRequest(0);
			EUMSSI.EventManager.trigger("CloseFilter");
		},

		_addItemToFilter : function(value){
			this.storedValue = "meta.source.keywords" + ":" + value;
			EUMSSI.FilterManager.addFilter("meta.source.keywords", this.storedValue, this.id, "Keyword: "+value);
		},

		/**
		 * TODO mejorar este comportamiento para que no busque por ID T_T
		 * @param event
		 * @private
		 */
		_addQueryToFilter : function(event){
			$("#generated-GENERAL_SEARCH").find("input").val($(event.target).html()).blur();
		},

		/**
		 * Retrieves the relative search entities, keywords and suggested queries from the service
		 * TODO change to the Webservice when ready
		 * @param text
		 * @private
		 */
		_retrieveRelatedFilters : function(text){
			var responseObj = {
				entities : ["Merkel", "Germany", "USA", "Spain"],
				keywords : ["fracking", "soccer", "euro", "nuclear", "refugee"],
				queries : ["Greenpeace against fracking", "Merkel meeting", "refugee crisis", "Messi vs Ronaldo"]
			};
			this._onGetRelatedFilters(responseObj);
		}

	});

})(jQuery);